(define (make-account balance password)
  (let ((count 0))
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (call-the-cops)
    (display "Called 911"))
  (define (dispatch pw m)
    (if (eq? pw password)
    (begin (set! count 0) (cond ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown request -- MAKE-ACCOUNT"
                       m))))
    (begin (set! count (+ count 1)) (display "Incorrect password") (display count)
           (if (= count 8) (call-the-cops) nil))
    ))
  dispatch))

(define acc (make-account 100 'secret-password))
((acc 'secret-password 'withdraw) 140)
((acc 'some-other-password 'deposit) 50)

