(define ( mul a b)
    (define (double a)
        (* a 2))
    (define (halve a)
        (/ a 2))
    (define (fast-mul a b n)
        (cond ((= b 0)  n)
                ((even? b) (fast-mul (double a) (halve b) n))
                (else (fast-mul a (- b 1) (+ a n)))))
    (fast-mul a b 0))
